# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YESWA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'IQKeyboardManagerSwift'
pod 'Kingfisher'
pod 'SwiftSpinner'
pod 'SWRevealViewController'
pod 'ReachabilitySwift', '~> 3'
pod 'Alamofire'
pod 'SDWebImage'
pod 'GoogleMaps'
pod 'GooglePlaces’
pod 'DKImagePickerController'
pod 'NHRangeSlider', '~> 0.2'

end
